// After `vite build`: write dist/sw.js that pre-caches every built file for offline use.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";

const dist = new URL("../dist/", import.meta.url).pathname;
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (name !== "sw.js") files.push(relative(dist, p).split("\\").join("/"));
  }
})(dist);
const list = ["./", ...files.sort()];
const version = createHash("sha1").update(list.join("|")).digest("hex").slice(0, 10);
writeFileSync(join(dist, "sw.js"), `// Generated by tools/write-sw.mjs
const CACHE = "wuling-grok-${version}";
const FILES = ${JSON.stringify(list)};
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then((res) => {
    if (res.ok && new URL(e.request.url).origin === location.origin) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); }
    return res;
  })));
});
`);
console.log("sw.js: cached", list.length, "files, version", version);
